interface=ap0
driver=nl80211
ssid=PortraitAdBlock
country_code=MX
hw_mode=g
channel=6
ieee80211n=1
wpa=2
wpa_passphrase=CHANGE_ME_MIN_8_CHARS
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
auth_algs=1
wmm_enabled=1
ignore_broadcast_ssid=0
